"use client"

import { useRef, useState } from "react"
import { MessageBubble, type Message } from "@/components/chat/message-bubble"
import { ChatInput } from "@/components/chat/chat-input"
import { ChatHeader } from "@/components/chat/chat-header"
import { ShareDialog } from "@/components/chat/share-dialog"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Button } from "@/components/ui/button"
import Link from "next/link"

function generateShareCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
  let code = ''
  for (let i = 0; i < 6; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return code
}

export default function ChatPage() {
  const [messages, setMessages] = useState<Message[]>([])
  const [isLoading, setIsLoading] = useState(false)
  const [chatTitle, setChatTitle] = useState<string>("")
  const [shareCode, setShareCode] = useState<string>("")
  const [shareDialogOpen, setShareDialogOpen] = useState(false)


  const nextIdRef = useRef(0);

const getNextId = () => {
  nextIdRef.current += 1;
  return nextIdRef.current.toString();
};

  const handleSendMessage = async (content: string) => {
    // Add user message
    const userMessage: Message = {
      id: getNextId(),
      role: "user",
      content,
      timestamp: new Date(),
    };

    setMessages((prev) => {
      const newMessages = [...prev, userMessage]
      if (newMessages.length === 1) {
        const title = content.length > 50 ? content.substring(0, 50) + "..." : content
        setChatTitle(title)
        setShareCode(generateShareCode())
      }
      return newMessages
    })
    setIsLoading(true)

    setTimeout(() => {
      const aiMessage: Message = {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content:
          "This is a placeholder response. In a real implementation, this would be generated by your RAG backend using the uploaded documents as context. The AI would retrieve relevant information from your knowledge base and provide an accurate, contextual answer.",
        sources: [
          { title: "Example Document.pdf", page: 5 },
          { title: "Research Paper.pdf", page: 12 },
        ],
        timestamp: new Date(),
      }
      setMessages((prev) => [...prev, aiMessage])
      setIsLoading(false)
    }, 1500)
  }

  const handleRename = () => {
    // TODO: Implement rename functionality
    console.log("Rename chat")
  }

  const handleDelete = () => {
    // TODO: Implement delete functionality
    console.log("Delete chat")
  }

  const handleShare = () => {
    setShareDialogOpen(true)
  }

  const examplePrompts = [
    "Summarize the main points from my documents",
    "What are the key findings in the research?",
    "Explain the methodology used",
    "Compare the different approaches discussed",
  ]

  return (
    <>
      <ShareDialog open={shareDialogOpen} onOpenChange={setShareDialogOpen} shareCode={shareCode} />
      <div className="h-full flex flex-col">
        <ChatHeader
          title={chatTitle}
          onRename={handleRename}
          onDelete={handleDelete}
          onShare={handleShare}
        />
        {messages.length === 0 ? (
        // Empty state
        <div className="flex-1 flex items-center justify-center p-8 bg-white dark:bg-black">
          <div className="max-w-2xl w-full space-y-8">
            <div className="text-center space-y-3">
              <h2 className="text-3xl font-semibold text-black dark:text-white">
                Start a conversation
              </h2>
              <p className="text-gray-600 dark:text-gray-400">
                Ask questions about your documents and get intelligent answers
              </p>
            </div>
            <div className="space-y-3">
              <p className="text-sm font-medium text-gray-500 dark:text-gray-500 text-center">
                Try asking:
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {examplePrompts.map((prompt, idx) => (
                  <button
                    key={idx}
                    onClick={() => handleSendMessage(prompt)}
                    className="p-4 text-left border border-gray-200 dark:border-gray-800 rounded-lg hover:bg-gray-50 dark:hover:bg-gray-900 transition-colors"
                  >
                    <p className="text-sm text-gray-700 dark:text-gray-300">{prompt}</p>
                  </button>
                ))}
              </div>
            </div>
            <div className="text-center pt-4">
              <p className="text-sm text-gray-500 dark:text-gray-500 mb-3">
                No documents yet?
              </p>
              <Link href="/chat/knowledge">
                <Button
                  variant="outline"
                  className="border-gray-300 dark:border-gray-700"
                >
                  Upload Documents
                </Button>
              </Link>
            </div>
          </div>
        </div>
      ) : (
        // Chat messages
        <ScrollArea className="flex-1 p-3">
          <div className="max-w-4xl mx-auto">
            {messages.map((message) => (
              <MessageBubble key={message.id} message={message} />
            ))}
          </div>
        </ScrollArea>
      )}
      <ChatInput onSendMessage={handleSendMessage} isLoading={isLoading} />
      </div>
    </>
  )
}
